---
title: "Conclusiones"
---
Nuestros resultados no se corresponden con la literatura revisada en los antecedentes (como Méndez Layera et al., 2020), especificamente respecto a la afirmacion de que las clases bajas sienten más temor por su vulnerabilidad social y residencial. Según nuestros resultados, todas las clases sociales tienen percepciones similares de la inseguiridad y el crimen. Como hipótesis tentativa, esta homogeneidad podría estar relacionada al rol amplificador de los medios de comunicación planteado por Klein (2010), el cual podria haber contribuido a nivelar el temor en el debate público chileno. Dado que este estudio presenta la limitación metodológica de no haber controlado por el consumo medial o la victimización directa e indirecta, se requieren futuras investigaciones para evaluar formalmente la validez de estas hipótesis en el Chile actual.
Nuestro resultados noss llevan a sugerir que las politicas públicas no debiesen limitarse exclusivamente al control policial o a programas tradicionales de prevención del delito. Por el contrario, los datos evidencian la necesidad de priorizar el fortalecimiento de la probidad y la transparencia en la gestión pública, dado que los servicios estatales constituyen un lugar donde los estratos socioeconómicos bajos y medios experimentan de manera más directa los efectos de la corrupción como una manifestación de desigualdades estructurales.