{
  "hash": "b7f4ab097a60d5741316e2c50b2bbc05",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Resultados\"\n---\n\n::: {.cell}\n\n:::\n\n\n\n\n::: {.cell}\n\n:::\n\n\n## Hipotesis de diferencias\nPara la hipótesis de diferencias de medias, donde se espera que exista una diferencia entre los promedios de percepción de la delincuencia entre clases sociales subjetivas bajas, medias y altas, se realizó un análisis ANOVA para comparar las medias de la escala de percepción de la delincuencia común entre los diferentes grupos de clase social subjetiva. \n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n               Df Sum Sq Mean Sq F value Pr(>F)\nclase_grupos    2    182   91.19   0.697  0.498\nResiduals    1190 155587  130.75               \n7 observations deleted due to missingness\n```\n\n\n:::\n:::\n\n\nLos resultados indican que la clase social subjetiva no tiene un efecto significativo en la percepción de la delincuencia común, ya que el valor p es mayor a 0.05 (F(2, 1190) = 0.697, p = 0.498). Esto sugiere que no hay diferencias significativas en la percepción de la delincuencia común entre los diferentes grupos de clase social subjetiva, en consecuencia se acepta la hipótesis nula. \n\n## Hipotesis direccional\nPara la hipótesis direccional, donde se espera que las clases sociales subjetivas bajas perciban más delincuencia común relacionada a la violencia y el narcotráfico, mientras que las clases sociales subjetivas altas perciban más delincuencia relacionada a la corrupción y el fraude, se realizaron dos análisis ANOVA independientes, uno para la escala de percepción de la delincuencia común, que se muestra en la primera hipotésis y otro para la escala de percepción de la corrupción.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n               Df Sum Sq Mean Sq F value        Pr(>F)    \nclase_grupos    2  11424    5712   18.93 0.00000000805 ***\nResiduals    1190 359036     302                          \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n7 observations deleted due to missingness\n```\n\n\n:::\n:::\n\n\nLos resultados del análisis ANOVA para la escala de percepción de la delincuencia común indican que no hay diferencias significativas entre los grupos de clase social subjetiva (F(2, 1190) = 0.697, p = 0.498). Por otro lado, los resultados del análisis ANOVA para la escala de percepción de la corrupción indican que existen diferencias significativas entre los grupos de clase social subjetiva y la percepción de la corrupción.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = escala_corrupcion ~ clase_grupos, data = data)\n\n$clase_grupos\n                            diff       lwr        upr     p adj\nClase Baja-Clase Alta  16.495609 10.092588 22.8986304 0.0000000\nClase Media-Clase Alta 14.035878  7.681955 20.3898004 0.0000008\nClase Media-Clase Baja -2.459731 -4.878616 -0.0408469 0.0452095\n```\n\n\n:::\n:::\n\n\nPara verificar entre qué grupos existen diferencias significativas, se realizó la prueba post-hoc de Tukey. Se encuentra que la clase baja puntúa 16.5 puntos más alto que la clase alta en la escala de percepción de la corrupción, la clase media puntúa 14.04 puntos más alto que la clase alta y la clase media puntúa 2.46 puntos más bajo que la clase baja. Estos resultados son significativos y sugieren que las clases sociales subjetivas bajas y medias perciben más corrupción que las clases sociales subjetivas altas.\n\n![](output\\grafico-hipotesis2.png)\n\n## Hipotesis correlacional\nPara evaluar la hipotesis correlacional, donde se espera que exista una correlación negativa entre la percepción de la delincuencia y la clase social subjetiva, se realizó un análisis de correlación de Spearman entre la variable de clase social subjetiva y la escala de percepción de la delincuencia común.\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  data$clase_subjetiva and data$escala_delincuencia_comun\nS = 284667894, p-value = 0.8378\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n         rho \n-0.005932208 \n```\n\n\n:::\n:::\n\n\nLos resultados demuestran una ausencia de relación significativa entre la percepción de la delincuencia y la clase social subjetiva (rho = -0.005, p = 0.83). Dado que el valor p es mayor a 0.05, se acepta la hipótesis nula y se conncluye que la clase social subjetiva no está asociada con la percepción de la delincuencia común.\n\n## Interpretaciones\n\n\n## Limitaciones y aportes\n",
    "supporting": [
      "05-resultados_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}